const crypto = require("node:crypto");
const database = require("../database");
const AppError = require("../errors/app-error");
const ERROR_CODES = require("../constants/error-codes");
const createAdminContentRepository = require("../repositories/admin-content.repository");
const { writeAudit } = require("./audit.service");

function fail(code, message, statusCode = 409, details) { throw new AppError({ code, message, statusCode, details }); }
function bool(value) { return value === true || value === 1 || value === "1"; }
function num(value) { return Number(value || 0); }
function iso(value) { if (!value) return null; const date = value instanceof Date ? value : new Date(value); return Number.isNaN(date.getTime()) ? null : date.toISOString(); }
function json(value, fallback = []) { if (Array.isArray(value) || (value && typeof value === "object")) return value; try { return JSON.parse(value); } catch { return fallback; } }
function randomCode(prefix) { return `${prefix}-${Date.now().toString(36).toUpperCase()}-${crypto.randomBytes(3).toString("hex").toUpperCase()}`; }
function meta(context, request) { return { adminUserId: context.admin.id, requestId: request?.requestId || null, ipAddress: request?.ipAddress || null }; }
function mediaIdsForArticle(input) { return [...new Set([input.coverMediaId, ...input.body.filter((b) => b.type === "IMAGE").map((b) => b.mediaId)].filter(Boolean))]; }
function mediaIdsForRow(row) { return [...new Set([row.cover_media_id, ...json(row.body_json).filter((b) => String(b.type).toUpperCase() === "IMAGE").map((b) => String(b.mediaId))].filter(Boolean))]; }

function articleDto(row) { return { id: row.id, code: row.code, title: row.title, tag: row.tag, summary: row.summary, authorName: row.author_name, coverMediaId: row.cover_media_id, coverImageUrl: row.cover_image_url, body: json(row.body_json), readingMinutes: num(row.reading_minutes), status: row.status, isHot: bool(row.is_hot), version: num(row.version), publishedAt: iso(row.published_at), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function collectionDto(row) { return { id: row.id, code: row.code, title: row.title, latinTitle: row.latin_title || "", description: row.description, coverMediaId: row.cover_media_id, coverImageUrl: row.cover_image_url, productIds: row.product_ids || [], visible: bool(row.visible), sortOrder: num(row.sort_order), version: num(row.version), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function bannerDto(row) { return { id: row.id, title: row.title, subtitle: row.subtitle || "", imageMediaId: row.image_media_id, imageUrl: row.image_url, targetProductId: row.target_product_id || null, linkType: row.link_type, visible: bool(row.visible), sortOrder: num(row.sort_order), version: num(row.version), startsAt: iso(row.starts_at), endsAt: iso(row.ends_at), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function page(result, input, mapper) { return { items: result.rows.map(mapper), page: input.page, pageSize: input.pageSize, total: result.total, hasMore: input.page * input.pageSize < result.total }; }

function createAdminContentService({ sequelize = database.sequelize, repositoryFactory = createAdminContentRepository } = {}) {
  const repository = () => repositoryFactory({ sequelize });
  const transaction = (work) => sequelize.transaction((tx) => work(repositoryFactory({ sequelize, transaction: tx })));
  async function assertMedia(repo, ids) { if ((await repo.activeMedia(ids, true)).length !== ids.length) fail(ERROR_CODES.MEDIA_NOT_FOUND, "One or more media assets are unavailable", 409); }
  async function assertProducts(repo, ids) { if ((await repo.activeProducts(ids, true)).length !== ids.length) fail(ERROR_CODES.PRODUCT_NOT_FOUND, "One or more products are unavailable", 409); }

  async function listArticles(input) { return page(await repository().articles(input), input, articleDto); }
  async function getArticle(id) { const row = await repository().article(id); if (!row) fail(ERROR_CODES.ARTICLE_NOT_FOUND, "Article not found", 404); return articleDto(row); }
  async function createArticle(input, context, request) {
    const id = await transaction(async (repo) => {
      const ids = mediaIdsForArticle(input); await assertMedia(repo, ids);
      if (input.status === "PUBLISHED" && input.body.filter((b) => b.type !== "IMAGE").reduce((sum, b) => sum + b.text.length, 0) < 20) fail(ERROR_CODES.CONTENT_BLOCK_INVALID, "Published article text must contain at least 20 characters", 422);
      const articleId = await repo.insertArticle({ ...input, code: randomCode("A"), bodyJson: JSON.stringify(input.body) });
      await repo.refreshReferenceState(ids);
      await writeAudit(repo, { ...meta(context, request), module: "articles", action: "ARTICLE_CREATED", targetType: "ARTICLE", targetId: articleId, targetLabel: input.title, after: { title: input.title, status: input.status } });
      return articleId;
    });
    return getArticle(id);
  }
  async function updateArticle(input, context, request) {
    await transaction(async (repo) => {
      const before = await repo.article(input.articleId, true); if (!before) fail(ERROR_CODES.ARTICLE_NOT_FOUND, "Article not found", 404);
      if (num(before.version) !== input.version) fail(ERROR_CODES.RESOURCE_VERSION_CONFLICT, "Article was modified by another request", 409, { currentVersion: num(before.version) });
      const oldIds = mediaIdsForRow(before); const newIds = mediaIdsForArticle(input); await assertMedia(repo, newIds);
      if (input.status === "PUBLISHED" && input.body.filter((b) => b.type !== "IMAGE").reduce((sum, b) => sum + b.text.length, 0) < 20) fail(ERROR_CODES.CONTENT_BLOCK_INVALID, "Published article text must contain at least 20 characters", 422);
      await repo.updateArticle(before.id, { ...input, bodyJson: JSON.stringify(input.body) }); await repo.refreshReferenceState([...oldIds, ...newIds]);
      await writeAudit(repo, { ...meta(context, request), module: "articles", action: "ARTICLE_UPDATED", targetType: "ARTICLE", targetId: before.id, targetLabel: input.title, before: { title: before.title, status: before.status, version: num(before.version) }, after: { title: input.title, status: input.status, version: input.version + 1 } });
    });
    return getArticle(input.articleId);
  }
  async function deleteArticle(id, context, request) { await transaction(async (repo) => { const before = await repo.article(id, true); if (!before) fail(ERROR_CODES.ARTICLE_NOT_FOUND, "Article not found", 404); const ids = mediaIdsForRow(before); await repo.deleteArticle(id); await repo.refreshReferenceState(ids); await writeAudit(repo, { ...meta(context, request), module: "articles", action: "ARTICLE_DELETED", targetType: "ARTICLE", targetId: id, targetLabel: before.title, before: { status: before.status }, after: { deleted: true } }); }); return { id, deleted: true }; }

  async function listCollections(input) { return page(await repository().collections(input), input, collectionDto); }
  async function getCollection(id) { const row = await repository().collection(id); if (!row) fail(ERROR_CODES.COLLECTION_NOT_FOUND, "Collection not found", 404); return collectionDto(row); }
  async function createCollection(input, context, request) { const id = await transaction(async (repo) => { await assertMedia(repo, [input.coverMediaId]); await assertProducts(repo, input.productIds); const collectionId = await repo.insertCollection({ ...input, code: randomCode("COL") }); await repo.replaceCollectionProducts(collectionId, input.productIds); await repo.refreshReferenceState([input.coverMediaId]); await writeAudit(repo, { ...meta(context, request), module: "collections", action: "COLLECTION_CREATED", targetType: "COLLECTION", targetId: collectionId, targetLabel: input.title, after: { title: input.title, productIds: input.productIds } }); return collectionId; }); return getCollection(id); }
  async function updateCollection(input, context, request) { await transaction(async (repo) => { const before = await repo.collection(input.collectionId, true); if (!before) fail(ERROR_CODES.COLLECTION_NOT_FOUND, "Collection not found", 404); if (num(before.version) !== input.version) fail(ERROR_CODES.RESOURCE_VERSION_CONFLICT, "Collection was modified by another request", 409, { currentVersion: num(before.version) }); await assertMedia(repo, [input.coverMediaId]); await assertProducts(repo, input.productIds); await repo.updateCollection(before.id, input); await repo.replaceCollectionProducts(before.id, input.productIds); await repo.refreshReferenceState([before.cover_media_id, input.coverMediaId]); await writeAudit(repo, { ...meta(context, request), module: "collections", action: "COLLECTION_UPDATED", targetType: "COLLECTION", targetId: before.id, targetLabel: input.title, before: { title: before.title, version: num(before.version) }, after: { title: input.title, version: input.version + 1, productIds: input.productIds } }); }); return getCollection(input.collectionId); }
  async function deleteCollection(id, context, request) { await transaction(async (repo) => { const before = await repo.collection(id, true); if (!before) fail(ERROR_CODES.COLLECTION_NOT_FOUND, "Collection not found", 404); await repo.deleteCollection(id); await repo.refreshReferenceState([before.cover_media_id]); await writeAudit(repo, { ...meta(context, request), module: "collections", action: "COLLECTION_DELETED", targetType: "COLLECTION", targetId: id, targetLabel: before.title, after: { deleted: true } }); }); return { id, deleted: true }; }

  async function listBanners(input) { return page(await repository().banners(input), input, bannerDto); }
  async function getBanner(id) { const row = await repository().banner(id); if (!row) fail(ERROR_CODES.NOT_FOUND, "Banner not found", 404); return bannerDto(row); }
  async function assertBanner(repo, input) { await assertMedia(repo, [input.imageMediaId]); if (input.targetProductId) await assertProducts(repo, [input.targetProductId]); }
  function persistedBanner(input) { return { ...input, linkType: input.targetProductId ? "PRODUCT" : "NONE" }; }
  async function createBanner(input, context, request) { const id = await transaction(async (repo) => { await assertBanner(repo, input); const bannerId = await repo.insertBanner(persistedBanner(input)); await repo.refreshReferenceState([input.imageMediaId]); await writeAudit(repo, { ...meta(context, request), module: "homepage", action: "BANNER_CREATED", targetType: "BANNER", targetId: bannerId, targetLabel: input.title, after: { title: input.title, targetProductId: input.targetProductId } }); return bannerId; }); return getBanner(id); }
  async function updateBanner(input, context, request) { await transaction(async (repo) => { const before = await repo.banner(input.bannerId, true); if (!before) fail(ERROR_CODES.NOT_FOUND, "Banner not found", 404); if (num(before.version) !== input.version) fail(ERROR_CODES.RESOURCE_VERSION_CONFLICT, "Banner was modified by another request", 409, { currentVersion: num(before.version) }); await assertBanner(repo, input); await repo.updateBanner(before.id, persistedBanner(input)); await repo.refreshReferenceState([before.image_media_id, input.imageMediaId]); await writeAudit(repo, { ...meta(context, request), module: "homepage", action: "BANNER_UPDATED", targetType: "BANNER", targetId: before.id, targetLabel: input.title, before: { title: before.title, version: num(before.version) }, after: { title: input.title, version: input.version + 1 } }); }); return getBanner(input.bannerId); }
  async function deleteBanner(id, context, request) { await transaction(async (repo) => { const before = await repo.banner(id, true); if (!before) fail(ERROR_CODES.NOT_FOUND, "Banner not found", 404); await repo.deleteBanner(id); await repo.refreshReferenceState([before.image_media_id]); await writeAudit(repo, { ...meta(context, request), module: "homepage", action: "BANNER_DELETED", targetType: "BANNER", targetId: id, targetLabel: before.title, after: { deleted: true } }); }); return { id, deleted: true }; }
  async function reorderBanners(ids, context, request) { await transaction(async (repo) => { const current = (await repo.bannerIds(true)).map((row) => row.id); if (current.length !== ids.length || current.some((id) => !ids.includes(id))) fail(ERROR_CODES.HOMEPAGE_CONFIG_INVALID, "bannerIds must include every existing banner exactly once", 409); await repo.reorderBanners(ids); await writeAudit(repo, { ...meta(context, request), module: "homepage", action: "BANNERS_REORDERED", targetType: "HOMEPAGE", targetId: "1", before: { bannerIds: current }, after: { bannerIds: ids } }); }); return { bannerIds: ids }; }

  async function getHome() { const row = await repository().home(); return { featuredTitle: row.settings.featured_title, showFeatured: bool(row.settings.show_featured), showCollections: bool(row.settings.show_collections), showJournal: bool(row.settings.show_journal), version: num(row.settings.version), updatedAt: iso(row.settings.updated_at), quickCategories: row.quickCategories.map((item) => ({ categoryId: item.category_id, name: item.name, iconText: item.icon_text, sortOrder: num(item.sort_order) })), featuredProducts: row.featuredProducts.map((item) => ({ productId: item.product_id, name: item.name, sortOrder: num(item.sort_order) })) }; }
  async function updateHome(input, context, request) { await transaction(async (repo) => { const before = await repo.lockHome(); if (num(before.version) !== input.version) fail(ERROR_CODES.RESOURCE_VERSION_CONFLICT, "Homepage settings were modified by another request", 409, { currentVersion: num(before.version) }); await repo.updateHome(input, context.admin.id); await writeAudit(repo, { ...meta(context, request), module: "homepage", action: "HOMEPAGE_SETTINGS_UPDATED", targetType: "HOMEPAGE", targetId: "1", before: { version: num(before.version) }, after: { ...input, version: input.version + 1 } }); }); return getHome(); }
  async function setQuickCategories(input, context, request) { await transaction(async (repo) => { const ids = input.items.map((item) => item.categoryId); const homeRow = await repo.lockHome(); if (num(homeRow.version) !== input.version) fail(ERROR_CODES.RESOURCE_VERSION_CONFLICT, "Homepage configuration was modified by another request", 409, { currentVersion: num(homeRow.version) }); if ((await repo.productCategories(ids, true)).length !== ids.length) fail(ERROR_CODES.CATEGORY_NOT_FOUND, "Quick categories must reference enabled product categories", 409); const before = await repo.home(); await repo.replaceQuickCategories(input.items); await repo.bumpHome(context.admin.id); await writeAudit(repo, { ...meta(context, request), module: "homepage", action: "HOME_QUICK_CATEGORIES_UPDATED", targetType: "HOMEPAGE", targetId: "1", before: { items: before.quickCategories }, after: { items: input.items, version: input.version + 1 } }); }); return getHome(); }
  async function setFeaturedProducts(input, context, request) { await transaction(async (repo) => { const homeRow = await repo.lockHome(); if (num(homeRow.version) !== input.version) fail(ERROR_CODES.RESOURCE_VERSION_CONFLICT, "Homepage configuration was modified by another request", 409, { currentVersion: num(homeRow.version) }); await assertProducts(repo, input.productIds); const before = await repo.home(); await repo.replaceFeaturedProducts(input.productIds); await repo.bumpHome(context.admin.id); await writeAudit(repo, { ...meta(context, request), module: "homepage", action: "HOME_FEATURED_PRODUCTS_UPDATED", targetType: "HOMEPAGE", targetId: "1", before: { productIds: before.featuredProducts.map((item) => item.product_id) }, after: { productIds: input.productIds, version: input.version + 1 } }); }); return getHome(); }

  return { listArticles, getArticle, createArticle, updateArticle, deleteArticle, listCollections, getCollection, createCollection, updateCollection, deleteCollection, listBanners, getBanner, createBanner, updateBanner, deleteBanner, reorderBanners, getHome, updateHome, setQuickCategories, setFeaturedProducts };
}

module.exports = { createAdminContentService, articleDto, collectionDto, bannerDto };
