const database = require('../database');
const AppError = require('../errors/app-error');
const createRepository = require('../repositories/admin-user.repository');
const { hashPassword } = require('../utils/password');
const { writeAudit } = require('./audit.service');
function iso(value) { if (!value) return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date.toISOString(); }
function dto(row) { return { id: row.id, username: row.username, name: row.name, status: row.status, role: { id: row.role_id, code: row.role_code, name: row.role_name }, lastLoginAt: iso(row.last_login_at), passwordChangedAt: iso(row.password_changed_at), createdAt: iso(row.created_at), updatedAt: iso(row.updated_at) }; }
function fail(code, message, statusCode, details) { throw new AppError({ code, message, statusCode, details }); }
function createAdminUserService({ sequelize = database.sequelize, repositoryFactory = createRepository } = {}) {
  const repo = () => repositoryFactory({ sequelize }); const transaction = (work) => sequelize.transaction((tx) => work(repositoryFactory({ sequelize, transaction: tx })));
  async function roles() { return { items: (await repo().listRoles()).map((item) => ({ id: item.id, code: item.code, name: item.name, description: item.description || '' })) }; }
  async function users() { return { items: (await repo().listUsers()).map(dto) }; }
  async function create(input, context, meta) { const id = await transaction(async (repository) => { if (await repository.usernameTaken(input.username)) fail('CONFLICT', 'Administrator username already exists', 409, { field: 'username' }); const role = await repository.roleByCode(input.roleCode); if (!role) fail('NOT_FOUND', 'Administrator role is unavailable', 409, { field: 'roleCode' }); const userId = await repository.insertUser({ username: input.username, passwordHash: await hashPassword(input.password), name: input.name, roleId: role.id, status: input.status }); await writeAudit(repository, { adminUserId: context.admin.id, module: 'admins', action: 'ADMIN_USER_CREATED', targetType: 'ADMIN_USER', targetId: userId, targetLabel: input.username, requestId: meta.requestId, ipAddress: meta.ipAddress, after: { username: input.username, name: input.name, roleCode: input.roleCode, status: input.status } }); return userId; }); return dto(await repo().userById(id)); }
  async function update(input, context, meta) { await transaction(async (repository) => { const before = await repository.userById(input.adminUserId, true); if (!before) fail('NOT_FOUND', 'Administrator user not found', 404); const role = await repository.roleByCode(input.roleCode); if (!role) fail('NOT_FOUND', 'Administrator role is unavailable', 409, { field: 'roleCode' }); const demotesLastSuper = before.role_code === 'SUPER_ADMIN' && before.status === 'ACTIVE' && (input.status !== 'ACTIVE' || role.code !== 'SUPER_ADMIN'); if (demotesLastSuper && await repository.activeSuperCount(true) <= 1) fail('CONFLICT', 'At least one active super administrator is required', 409); if (String(before.id) === String(context.admin.id) && input.status !== 'ACTIVE') fail('FORBIDDEN', 'Current administrator cannot disable itself', 403); const passwordHash = input.password ? await hashPassword(input.password) : null; await repository.updateUser(before.id, { name: input.name, roleId: role.id, status: input.status, passwordHash }); if (input.status !== 'ACTIVE' || passwordHash || role.code !== before.role_code) await repository.revokeSessions(before.id); await writeAudit(repository, { adminUserId: context.admin.id, module: 'admins', action: 'ADMIN_USER_UPDATED', targetType: 'ADMIN_USER', targetId: before.id, targetLabel: before.username, requestId: meta.requestId, ipAddress: meta.ipAddress, before: { name: before.name, roleCode: before.role_code, status: before.status }, after: { name: input.name, roleCode: role.code, status: input.status, passwordChanged: Boolean(passwordHash) } }); }); return dto(await repo().userById(input.adminUserId)); }
  return { roles, users, create, update };
}
module.exports = { createAdminUserService };
